#SPDX-License-Identifier: MIT-0
---
# tasks file for dynamic_motd
- name: My first play
  hosts: localhost
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
   


